apiVersion: v1
kind: ConfigMap
metadata:
  name: my-python-app-config
data:
  DATABASE_HOST: "mysql"
  DATABASE_NAME: "mydb"
  DATABASE_USER: "root"
  DATABASE_PASSWORD: "root"
---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: my-python-app-secret
# type: Opaque
# data:
#   API_KEY: <base64-encoded API key>
#   SECRET_KEY: <base64-encoded secret key>
