---
- hosts: all
  gather_facts: false
  become: true
  vars:
    jenkins_admin_username: admin
    admin_username: admin
    admin_password: 1234
    jenkins_admin_password: your_admin_password_here
    jenkins_url: http://localhost:8080
    groovy_version: "4.0.9"
    ansible_python_interpreter: /usr/bin/python
    jenkins_home: "/var/lib/jenkins"
    jenkins_plugins:
      - git
      - pipeline
  tasks:
    - name: Update system packages
      yum:
        name: "*"
        state: latest
      become: true

    - name: Install OpenJDK 11
      become: true
      command: amazon-linux-extras install java-openjdk11 -y

    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins
        baseurl: http://pkg.jenkins-ci.org/redhat-stable
        gpgcheck: yes
        gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        enabled: yes
      tags: jenkins

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present
      tags: jenkins

    - name: Start Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
      tags: jenkins

    # - name: Wait for Jenkins to start
    #   wait_for:
    #     host: localhost
    #     port: 8080
    #     delay: 1
    #     timeout: 60
    #   tags: jenkins

    - name: Install Groovy
      yum:
        name:
          - groovy
        state: present

    - name: Create Jenkins post-init script directory
      file:
        path: /var/lib/jenkins/init.groovy.d
        state: directory
        mode: 0755
        owner: jenkins
        group: jenkins

    - name: Add Jenkins post-init script
      copy:
        content: |
          import jenkins.*
          import jenkins.model.*
          import hudson.security.*
          import jenkins.security.*
          import java.util.logging.Logger

          def logger = Logger.getLogger("")
          def instance = Jenkins.getInstance()

          // Disable Setup Wizard
          instance.setInstallState(Jenkins.InstallState.INITIAL_SETUP_COMPLETED)

          // Set up security realm
          def realm = new HudsonPrivateSecurityRealm(false)
          realm.createAccount("admin", "password")
          instance.setSecurityRealm(realm)

          // Set up authorization strategy
          def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
          strategy.setAllowAnonymousRead(false)
          instance.setAuthorizationStrategy(strategy)

          // Install plugins
          def githubPlugin = instance.getPluginManager().getPlugin("github")
          if (githubPlugin == null) {
              logger.info("Installing GitHub plugin...")
              instance.getPluginManager().installPlugin("github")
              logger.info("GitHub plugin installed.")
          }

          def pipelinePlugin = instance.getPluginManager().getPlugin("workflow-aggregator")
          if (pipelinePlugin == null) {
              logger.info("Installing Pipeline plugin...")
              instance.getPluginManager().installPlugin("workflow-aggregator")
              logger.info("Pipeline plugin installed.")
          }
          def pluginManager = instance.getPluginManager()
          def suggestedPlugins = pluginManager.getSuggestedPlugins()

          if (suggestedPlugins) {
            logger.info("Installing suggested plugins...")
            suggestedPlugins.each { plugin ->
              logger.info("Installing ${plugin.name}...")
              pluginManager.installPlugin(plugin.name)
              logger.info("${plugin.name} installed.")
            }
          }
          // Save changes
          instance.save()

        dest: /var/lib/jenkins/init.groovy.d/admin-user.groovy
        mode: 0644
        owner: jenkins
        group: jenkins

    - name: Restart Jenkins
      service:
        name: jenkins
        state: restarted
