version: '3'
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - '5000:5000'
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=devopsroles
    depends_on:
      - db
  db:
    image: mysql:5.6 
    ports:
      - '30000:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
